# Generated by Django 5.2.6 on 2025-09-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(help_text='Date of Birth FOR VERIFICATION PURPOSES ONLY PURSUANT TO 18 U.S.C. §§ 2256 ET SEQ.')),
                ('pronouns', models.CharField(choices=[('she/her', 'She/Her'), ('he/him', 'He/Him'), ('they/them', 'They/Them'), ('other', 'Other')], max_length=10)),
                ('social_handles', models.TextField(help_text='Instagram, Facebook, X, YouTube, TikTok, Twitch, Threads, Reddit, etc.')),
                ('ethnicity', models.CharField(choices=[('white', 'White'), ('black', 'Black/African American'), ('hispanic', 'Hispanic/Latino'), ('asian', 'Asian'), ('native_american', 'American Indian/Alaska Native'), ('pacific_islander', 'Native Hawaiian/Pacific Islander'), ('two_or_more', 'Two or more Races'), ('decline', 'Decline to Answer')], max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('how_did_you_hear', models.TextField()),
                ('employer_feelings', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('know_anyone', models.TextField(blank=True, null=True)),
                ('desired_prize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('competed_before', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('prior_url', models.URLField(blank=True, null=True)),
                ('registration_feep_aid', models.BooleanField(default=False)),
            ],
        ),
    ]
